/**
 * This code was generated by Builder.io.
 */

// checking code 
import * as React from "react";

function MyComponent(props) {
  return (
    <div className="bg-white flex flex-col items-stretch">
      <div className="flex-col overflow-hidden relative flex min-h-[810px] w-full items-stretch max-md:max-w-full">
        <img
          loading="lazy"
          srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/7080f35c877571117a9cdd8d6a6c19dd829221a54f96d868f44119919dbe7c8e?apiKey=e16cb3c994984815b737f967d633609a&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/7080f35c877571117a9cdd8d6a6c19dd829221a54f96d868f44119919dbe7c8e?apiKey=e16cb3c994984815b737f967d633609a&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/7080f35c877571117a9cdd8d6a6c19dd829221a54f96d868f44119919dbe7c8e?apiKey=e16cb3c994984815b737f967d633609a&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/7080f35c877571117a9cdd8d6a6c19dd829221a54f96d868f44119919dbe7c8e?apiKey=e16cb3c994984815b737f967d633609a&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/7080f35c877571117a9cdd8d6a6c19dd829221a54f96d868f44119919dbe7c8e?apiKey=e16cb3c994984815b737f967d633609a&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/7080f35c877571117a9cdd8d6a6c19dd829221a54f96d868f44119919dbe7c8e?apiKey=e16cb3c994984815b737f967d633609a&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/7080f35c877571117a9cdd8d6a6c19dd829221a54f96d868f44119919dbe7c8e?apiKey=e16cb3c994984815b737f967d633609a&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/7080f35c877571117a9cdd8d6a6c19dd829221a54f96d868f44119919dbe7c8e?apiKey=e16cb3c994984815b737f967d633609a&"
          className="absolute h-full w-full object-cover object-center inset-0"
        />
        <div className="relative bg-white z-[1] flex w-full justify-between gap-5 pl-11 pr-9 py-4 items-start max-md:max-w-full max-md:flex-wrap max-md:px-5">
          <div className="flex items-stretch justify-between gap-5">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/625907b047bc75a0afcd3ff3acbd1d9dcd6c9e9cdad210998b6e18299976338d?apiKey=e16cb3c994984815b737f967d633609a&"
              className="aspect-[1.09] object-contain object-center w-[37px] overflow-hidden shrink-0 max-w-full"
            />
            <div className="text-black text-2xl mt-1.5">MedicureAi</div>
          </div>
          <div className="justify-between items-start flex gap-5 max-md:max-w-full max-md:flex-wrap max-md:justify-center">
            <div className="text-black text-base font-semibold self-center whitespace-nowrap my-auto">
              Home
            </div>
            <div className="text-black text-base font-semibold self-center my-auto">
              About Us
            </div>
            <div className="text-black text-base font-semibold self-center my-auto">
              Services
            </div>
            <div className="text-black text-base font-semibold self-center my-auto">
              Our Doctors
            </div>
            <div className="text-black text-base font-semibold self-center my-auto">
              Appointment
            </div>
            <div className="text-white text-base font-semibold whitespace-nowrap rounded bg-rose-500 self-stretch grow justify-center items-stretch px-7 py-2.5 max-md:px-5">
              Book Appointment
            </div>
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/db80cb40371175f608f02ae1372de7b939d2120401475d8463e65e302f606309?apiKey=e16cb3c994984815b737f967d633609a&"
              className="aspect-[0.06] object-contain object-center w-0.5 overflow-hidden self-stretch shrink-0 max-w-full"
            />
            <div className="text-black text-base font-semibold whitespace-nowrap rounded border bg-white self-stretch grow justify-center items-stretch px-7 py-2.5 border-solid border-rose-500 max-md:px-5">
              Login
            </div>
          </div>
        </div>
        <div className="relative w-full pl-12 pt-12 max-md:max-w-full max-md:pl-5">
          <div className="gap-5 flex max-md:flex-col max-md:items-stretch max-md:gap-0">
            <div className="flex flex-col items-stretch w-[34%] max-md:w-full max-md:ml-0">
              <div className="relative flex flex-col my-auto items-start max-md:max-w-full max-md:mt-10">
                <div className="text-white text-7xl font-extrabold self-stretch max-md:max-w-full max-md:text-4xl">
                  Your Health Is{" "}
                </div>
                <div className="text-white text-opacity-0 text-7xl font-extrabold self-stretch mt-14 max-md:max-w-full max-md:text-4xl max-md:mt-10">
                  Our Priority.
                </div>
                <div className="flex w-[327px] max-w-full flex-col items-stretch ml-3.5 mt-8 max-md:ml-2.5">
                  <div className="text-white text-sm">
                    Empowering healthcare with MedicureAi: AI-driven diagnostics
                    for accurate, timely treatment. Bridging gaps in rural
                    areas, advancing medical accessibility and outcomes
                  </div>
                  <div className="text-white text-base font-semibold rounded bg-rose-500 justify-center items-stretch mt-14 px-7 py-2.5 max-md:mt-10 max-md:px-5">
                    Book Appointment
                  </div>
                </div>
              </div>
            </div>
            <div className="flex flex-col items-stretch w-[66%] ml-5 max-md:w-full max-md:ml-0">
              <img
                loading="lazy"
                srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/ff918cfbcf4c2aa76ccdaaf72c3d9448311ade412ac9bae840124e543dbc3eb9?apiKey=e16cb3c994984815b737f967d633609a&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/ff918cfbcf4c2aa76ccdaaf72c3d9448311ade412ac9bae840124e543dbc3eb9?apiKey=e16cb3c994984815b737f967d633609a&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/ff918cfbcf4c2aa76ccdaaf72c3d9448311ade412ac9bae840124e543dbc3eb9?apiKey=e16cb3c994984815b737f967d633609a&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/ff918cfbcf4c2aa76ccdaaf72c3d9448311ade412ac9bae840124e543dbc3eb9?apiKey=e16cb3c994984815b737f967d633609a&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/ff918cfbcf4c2aa76ccdaaf72c3d9448311ade412ac9bae840124e543dbc3eb9?apiKey=e16cb3c994984815b737f967d633609a&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/ff918cfbcf4c2aa76ccdaaf72c3d9448311ade412ac9bae840124e543dbc3eb9?apiKey=e16cb3c994984815b737f967d633609a&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/ff918cfbcf4c2aa76ccdaaf72c3d9448311ade412ac9bae840124e543dbc3eb9?apiKey=e16cb3c994984815b737f967d633609a&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/ff918cfbcf4c2aa76ccdaaf72c3d9448311ade412ac9bae840124e543dbc3eb9?apiKey=e16cb3c994984815b737f967d633609a&"
                className="aspect-[1.29] object-contain object-center w-full overflow-hidden grow mt-7 max-md:max-w-full max-md:mt-10"
              />
            </div>
          </div>
        </div>
      </div>
      <div className="text-rose-500 text-5xl font-bold self-center whitespace-nowrap ml-14 mt-20 max-md:text-4xl max-md:mt-10">
        About Us
      </div>
      <div className="self-center w-full max-w-[1204px] mt-3.5 max-md:max-w-full">
        <div className="gap-5 flex max-md:flex-col max-md:items-stretch max-md:gap-0">
          <div className="flex flex-col items-stretch w-[44%] max-md:w-full max-md:ml-0">
            <img
              loading="lazy"
              srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/b0065f06189d1bd9d07cdfad88b786c651a47033920a532f7c0acd2bf6bb592d?apiKey=e16cb3c994984815b737f967d633609a&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/b0065f06189d1bd9d07cdfad88b786c651a47033920a532f7c0acd2bf6bb592d?apiKey=e16cb3c994984815b737f967d633609a&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/b0065f06189d1bd9d07cdfad88b786c651a47033920a532f7c0acd2bf6bb592d?apiKey=e16cb3c994984815b737f967d633609a&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/b0065f06189d1bd9d07cdfad88b786c651a47033920a532f7c0acd2bf6bb592d?apiKey=e16cb3c994984815b737f967d633609a&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/b0065f06189d1bd9d07cdfad88b786c651a47033920a532f7c0acd2bf6bb592d?apiKey=e16cb3c994984815b737f967d633609a&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/b0065f06189d1bd9d07cdfad88b786c651a47033920a532f7c0acd2bf6bb592d?apiKey=e16cb3c994984815b737f967d633609a&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/b0065f06189d1bd9d07cdfad88b786c651a47033920a532f7c0acd2bf6bb592d?apiKey=e16cb3c994984815b737f967d633609a&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/b0065f06189d1bd9d07cdfad88b786c651a47033920a532f7c0acd2bf6bb592d?apiKey=e16cb3c994984815b737f967d633609a&"
              className="aspect-[0.83] object-contain object-center w-full overflow-hidden grow max-md:max-w-full max-md:mt-10"
            />
          </div>
          <div className="flex flex-col items-stretch w-[56%] ml-5 max-md:w-full max-md:ml-0">
            <div className="flex flex-col my-auto px-5 max-md:max-w-full max-md:mt-10">
              <div className="text-black text-lg self-stretch max-md:max-w-full">
                At MedicureAi, we're more than just a tech-driven healthcare
                platform; we're a catalyst for positive change. Founded on the
                belief that quality healthcare should be accessible to all, we
                bring together a diverse team of medical professionals, data
                scientists, and tech enthusiasts. Our mission is simple yet
                profound: to leverage the power of artificial intelligence for
                precision diagnostics, making healthcare smarter, faster, and
                within reach.
              </div>
              <div className="flex items-stretch justify-between gap-5 mt-10 self-start">
                <img
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/01d2b8d90f54f4b3adb28c61a597ba29922146212e94817aab51bae662db3633?apiKey=e16cb3c994984815b737f967d633609a&"
                  className="aspect-square object-contain object-center w-[35px] overflow-hidden shrink-0 max-w-full"
                />
                <div className="text-black text-lg self-center grow shrink basis-auto my-auto">
                  Accessible Diagnostics for All
                </div>
              </div>
              <div className="flex items-stretch justify-between gap-5 mt-3.5 self-start">
                <img
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/01d2b8d90f54f4b3adb28c61a597ba29922146212e94817aab51bae662db3633?apiKey=e16cb3c994984815b737f967d633609a&"
                  className="aspect-square object-contain object-center w-[35px] overflow-hidden shrink-0 max-w-full"
                />
                <div className="text-black text-lg self-center grow whitespace-nowrap my-auto">
                  Personalized Precision Medicine
                </div>
              </div>
              <div className="flex items-stretch justify-between gap-5 mt-3.5 self-start">
                <img
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/01d2b8d90f54f4b3adb28c61a597ba29922146212e94817aab51bae662db3633?apiKey=e16cb3c994984815b737f967d633609a&"
                  className="aspect-square object-contain object-center w-[35px] overflow-hidden shrink-0 max-w-full"
                />
                <div className="text-black text-lg self-center grow whitespace-nowrap my-auto">
                  Collaborative Community Health
                </div>
              </div>
              <div className="flex items-stretch justify-between gap-5 mt-3.5 self-start">
                <img
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/01d2b8d90f54f4b3adb28c61a597ba29922146212e94817aab51bae662db3633?apiKey=e16cb3c994984815b737f967d633609a&"
                  className="aspect-square object-contain object-center w-[35px] overflow-hidden shrink-0 max-w-full"
                />
                <div className="text-black text-lg self-center grow whitespace-nowrap my-auto">
                  Tech-Driven Healthcare Innovation
                </div>
              </div>
              <div className="flex items-stretch justify-between gap-5 mt-3.5 self-start">
                <img
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/01d2b8d90f54f4b3adb28c61a597ba29922146212e94817aab51bae662db3633?apiKey=e16cb3c994984815b737f967d633609a&"
                  className="aspect-square object-contain object-center w-[35px] overflow-hidden shrink-0 max-w-full"
                />
                <div className="text-black text-lg self-center grow whitespace-nowrap my-auto">
                  Patient-Centric Wellness Advocacy
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="flex-col overflow-hidden relative flex min-h-[786px] w-full justify-center items-stretch mt-24 max-md:max-w-full max-md:mt-10">
        <img
          loading="lazy"
          srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/624a849dfbb97a922adcbab6191d02685a591a16e0563abd933b94e4c37ef470?apiKey=e16cb3c994984815b737f967d633609a&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/624a849dfbb97a922adcbab6191d02685a591a16e0563abd933b94e4c37ef470?apiKey=e16cb3c994984815b737f967d633609a&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/624a849dfbb97a922adcbab6191d02685a591a16e0563abd933b94e4c37ef470?apiKey=e16cb3c994984815b737f967d633609a&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/624a849dfbb97a922adcbab6191d02685a591a16e0563abd933b94e4c37ef470?apiKey=e16cb3c994984815b737f967d633609a&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/624a849dfbb97a922adcbab6191d02685a591a16e0563abd933b94e4c37ef470?apiKey=e16cb3c994984815b737f967d633609a&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/624a849dfbb97a922adcbab6191d02685a591a16e0563abd933b94e4c37ef470?apiKey=e16cb3c994984815b737f967d633609a&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/624a849dfbb97a922adcbab6191d02685a591a16e0563abd933b94e4c37ef470?apiKey=e16cb3c994984815b737f967d633609a&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/624a849dfbb97a922adcbab6191d02685a591a16e0563abd933b94e4c37ef470?apiKey=e16cb3c994984815b737f967d633609a&"
          className="absolute h-full w-full object-cover object-center inset-0"
        />
        <div className="relative flex w-full flex-col items-center pt-12 px-16 max-md:max-w-full max-md:px-5">
          <div className="flex w-full max-w-[1117px] flex-col items-stretch max-md:max-w-full">
            <div className="text-white text-6xl font-medium self-center whitespace-nowrap max-md:text-4xl">
              Services
            </div>
            <div className="mt-24 max-md:max-w-full max-md:mt-10">
              <div className="gap-5 flex max-md:flex-col max-md:items-stretch max-md:gap-0">
                <div className="flex flex-col items-stretch w-3/12 max-md:w-full max-md:ml-0">
                  <div className="bg-white flex grow flex-col items-stretch w-full pl-5 pr-3 py-8 rounded-xl max-md:mt-10">
                    <img
                      loading="lazy"
                      srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/964e9ae5-ce4f-4f85-a83f-35da2089c024?apiKey=e16cb3c994984815b737f967d633609a&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/964e9ae5-ce4f-4f85-a83f-35da2089c024?apiKey=e16cb3c994984815b737f967d633609a&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/964e9ae5-ce4f-4f85-a83f-35da2089c024?apiKey=e16cb3c994984815b737f967d633609a&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/964e9ae5-ce4f-4f85-a83f-35da2089c024?apiKey=e16cb3c994984815b737f967d633609a&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/964e9ae5-ce4f-4f85-a83f-35da2089c024?apiKey=e16cb3c994984815b737f967d633609a&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/964e9ae5-ce4f-4f85-a83f-35da2089c024?apiKey=e16cb3c994984815b737f967d633609a&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/964e9ae5-ce4f-4f85-a83f-35da2089c024?apiKey=e16cb3c994984815b737f967d633609a&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/964e9ae5-ce4f-4f85-a83f-35da2089c024?apiKey=e16cb3c994984815b737f967d633609a&"
                      className="aspect-square object-contain object-center w-[69px] overflow-hidden self-center max-w-full rounded-[50%]"
                    />
                    <div className="text-black text-2xl font-medium self-center whitespace-nowrap mt-6">
                      Cardiology
                    </div>
                    <div className="overflow-hidden text-black text-center text-ellipsis text-sm mt-8">
                      Cardiologist, is a medical professional specializing in
                      the diagnosis, treatment, and prevention of diseases and
                      conditions related to the cardiovascular system
                    </div>
                  </div>
                </div>
                <div className="flex flex-col items-stretch w-3/12 ml-5 max-md:w-full max-md:ml-0">
                  <div className="bg-white flex grow flex-col items-stretch w-full pl-4 pr-3 py-8 rounded-xl max-md:mt-10">
                    <img
                      loading="lazy"
                      srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/5c1e1bf5-0577-404d-93b7-b9650f534087?apiKey=e16cb3c994984815b737f967d633609a&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/5c1e1bf5-0577-404d-93b7-b9650f534087?apiKey=e16cb3c994984815b737f967d633609a&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/5c1e1bf5-0577-404d-93b7-b9650f534087?apiKey=e16cb3c994984815b737f967d633609a&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/5c1e1bf5-0577-404d-93b7-b9650f534087?apiKey=e16cb3c994984815b737f967d633609a&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/5c1e1bf5-0577-404d-93b7-b9650f534087?apiKey=e16cb3c994984815b737f967d633609a&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/5c1e1bf5-0577-404d-93b7-b9650f534087?apiKey=e16cb3c994984815b737f967d633609a&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/5c1e1bf5-0577-404d-93b7-b9650f534087?apiKey=e16cb3c994984815b737f967d633609a&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/5c1e1bf5-0577-404d-93b7-b9650f534087?apiKey=e16cb3c994984815b737f967d633609a&"
                      className="aspect-square object-contain object-center w-[69px] overflow-hidden self-center max-w-full rounded-[50%]"
                    />
                    <div className="text-black text-2xl font-medium self-center whitespace-nowrap mt-6">
                      Psychologists
                    </div>
                    <div className="overflow-hidden text-black text-center text-ellipsis text-sm mt-8">
                      Psychologists, who are experts in psychology, explore
                      various aspects of human cognition, emotion, and behavior
                      to understand mental processes and promote mental health.
                    </div>
                  </div>
                </div>
                <div className="flex flex-col items-stretch w-3/12 ml-5 max-md:w-full max-md:ml-0">
                  <div className="bg-white flex grow flex-col items-stretch w-full px-5 py-8 rounded-xl max-md:mt-10">
                    <img
                      loading="lazy"
                      srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/551dae8a-3c7d-4040-a676-039781e57919?apiKey=e16cb3c994984815b737f967d633609a&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/551dae8a-3c7d-4040-a676-039781e57919?apiKey=e16cb3c994984815b737f967d633609a&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/551dae8a-3c7d-4040-a676-039781e57919?apiKey=e16cb3c994984815b737f967d633609a&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/551dae8a-3c7d-4040-a676-039781e57919?apiKey=e16cb3c994984815b737f967d633609a&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/551dae8a-3c7d-4040-a676-039781e57919?apiKey=e16cb3c994984815b737f967d633609a&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/551dae8a-3c7d-4040-a676-039781e57919?apiKey=e16cb3c994984815b737f967d633609a&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/551dae8a-3c7d-4040-a676-039781e57919?apiKey=e16cb3c994984815b737f967d633609a&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/551dae8a-3c7d-4040-a676-039781e57919?apiKey=e16cb3c994984815b737f967d633609a&"
                      className="aspect-square object-contain object-center w-[69px] overflow-hidden self-center max-w-full rounded-[50%]"
                    />
                    <div className="text-black text-2xl font-medium self-center whitespace-nowrap mt-6">
                      Gynecologists
                    </div>
                    <div className="overflow-hidden text-black text-center text-ellipsis text-sm mt-8">
                      Gynecologists are trained to diagnose and treat various
                      conditions related to women's reproductive health, provide
                      prenatal care during pregnancy, perform surgeries, and
                      offer guidance on family planning and contraception.
                    </div>
                  </div>
                </div>{" "}
                <div className="flex flex-col items-stretch w-3/12 ml-5 max-md:w-full max-md:ml-0">
                  <div className="bg-white flex grow flex-col items-stretch w-full px-4 py-8 rounded-xl max-md:mt-10">
                    <img
                      loading="lazy"
                      srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/81032ab1-c734-414b-8b2a-490e0d609536?apiKey=e16cb3c994984815b737f967d633609a&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/81032ab1-c734-414b-8b2a-490e0d609536?apiKey=e16cb3c994984815b737f967d633609a&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/81032ab1-c734-414b-8b2a-490e0d609536?apiKey=e16cb3c994984815b737f967d633609a&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/81032ab1-c734-414b-8b2a-490e0d609536?apiKey=e16cb3c994984815b737f967d633609a&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/81032ab1-c734-414b-8b2a-490e0d609536?apiKey=e16cb3c994984815b737f967d633609a&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/81032ab1-c734-414b-8b2a-490e0d609536?apiKey=e16cb3c994984815b737f967d633609a&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/81032ab1-c734-414b-8b2a-490e0d609536?apiKey=e16cb3c994984815b737f967d633609a&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/81032ab1-c734-414b-8b2a-490e0d609536?apiKey=e16cb3c994984815b737f967d633609a&"
                      className="aspect-square object-contain object-center w-[69px] overflow-hidden self-center max-w-full rounded-[50%]"
                    />{" "}
                    <div className="text-black text-2xl font-medium self-center whitespace-nowrap mt-6">
                      Nephrologist
                    </div>{" "}
                    <div className="overflow-hidden text-black text-center text-ellipsis text-sm mt-8">
                      Nephrologists manage various kidney disorders, including
                      kidney disease, kidney stones, and electrolyte imbalances.
                      They are trained to provide medical interventions,
                      prescribe medications, and, if necessary, coordinate
                      kidney-related surgeries or procedures.
                    </div>
                  </div>
                </div>
              </div>
            </div>{" "}
            <img
              loading="lazy"
              srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/842d78bcef0b742500185c7940853ac3de74de3d54b7cc237447b5a7dc1879ed?apiKey=e16cb3c994984815b737f967d633609a&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/842d78bcef0b742500185c7940853ac3de74de3d54b7cc237447b5a7dc1879ed?apiKey=e16cb3c994984815b737f967d633609a&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/842d78bcef0b742500185c7940853ac3de74de3d54b7cc237447b5a7dc1879ed?apiKey=e16cb3c994984815b737f967d633609a&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/842d78bcef0b742500185c7940853ac3de74de3d54b7cc237447b5a7dc1879ed?apiKey=e16cb3c994984815b737f967d633609a&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/842d78bcef0b742500185c7940853ac3de74de3d54b7cc237447b5a7dc1879ed?apiKey=e16cb3c994984815b737f967d633609a&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/842d78bcef0b742500185c7940853ac3de74de3d54b7cc237447b5a7dc1879ed?apiKey=e16cb3c994984815b737f967d633609a&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/842d78bcef0b742500185c7940853ac3de74de3d54b7cc237447b5a7dc1879ed?apiKey=e16cb3c994984815b737f967d633609a&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/842d78bcef0b742500185c7940853ac3de74de3d54b7cc237447b5a7dc1879ed?apiKey=e16cb3c994984815b737f967d633609a&"
              className="aspect-[1.35] object-contain object-center w-[432px] overflow-hidden self-center max-w-full"
            />
          </div>
        </div>
      </div>{" "}
      <div className="text-rose-500 text-5xl font-bold self-center whitespace-nowrap mt-20 max-md:text-4xl max-md:mt-10">
        Our Doctors
      </div>{" "}
      <div className="self-center w-full max-w-[1167px] mt-28 px-5 max-md:max-w-full max-md:mt-10">
        <div className="gap-5 flex max-md:flex-col max-md:items-stretch max-md:gap-0">
          <div className="flex flex-col items-stretch w-[33%] max-md:w-full max-md:ml-0">
            <div className="shadow-sm bg-white flex w-full grow flex-col items-stretch mx-auto pt-9 pb-2.5 rounded-xl max-md:mt-10">
              <div className="flex items-center justify-between gap-4 pr-20 max-md:pr-5">
                <div className="flex-col overflow-hidden relative flex aspect-[2.25] items-stretch gap-1.5 my-auto pl-1.5 pr-8 py-2 max-md:pr-5">
                  <img
                    loading="lazy"
                    srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/882ba82a88a20667caa55b89548bc9cde4d3fc5db63c2ecc18161393ef886921?apiKey=e16cb3c994984815b737f967d633609a&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/882ba82a88a20667caa55b89548bc9cde4d3fc5db63c2ecc18161393ef886921?apiKey=e16cb3c994984815b737f967d633609a&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/882ba82a88a20667caa55b89548bc9cde4d3fc5db63c2ecc18161393ef886921?apiKey=e16cb3c994984815b737f967d633609a&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/882ba82a88a20667caa55b89548bc9cde4d3fc5db63c2ecc18161393ef886921?apiKey=e16cb3c994984815b737f967d633609a&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/882ba82a88a20667caa55b89548bc9cde4d3fc5db63c2ecc18161393ef886921?apiKey=e16cb3c994984815b737f967d633609a&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/882ba82a88a20667caa55b89548bc9cde4d3fc5db63c2ecc18161393ef886921?apiKey=e16cb3c994984815b737f967d633609a&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/882ba82a88a20667caa55b89548bc9cde4d3fc5db63c2ecc18161393ef886921?apiKey=e16cb3c994984815b737f967d633609a&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/882ba82a88a20667caa55b89548bc9cde4d3fc5db63c2ecc18161393ef886921?apiKey=e16cb3c994984815b737f967d633609a&"
                    className="absolute h-full w-full object-cover object-center inset-0"
                  />{" "}
                  <div className="flex-col relative overflow-hidden flex aspect-square justify-center items-center flex-1">
                    <img
                      loading="lazy"
                      src="https://cdn.builder.io/api/v1/image/assets/TEMP/b13ee23a89b4a39706fc7e53758353fad5abfa1b0648d7b7b671dbcfec28c74e?apiKey=e16cb3c994984815b737f967d633609a&"
                      className="absolute h-full w-full object-cover object-center inset-0"
                    />{" "}
                    <img
                      loading="lazy"
                      src="https://cdn.builder.io/api/v1/image/assets/TEMP/b13ee23a89b4a39706fc7e53758353fad5abfa1b0648d7b7b671dbcfec28c74e?apiKey=e16cb3c994984815b737f967d633609a&"
                      className="aspect-square object-contain object-center w-full overflow-hidden"
                    />
                  </div>{" "}
                  <div className="relative text-black text-sm font-bold self-center my-auto">
                    4.3
                  </div>
                </div>{" "}
                <div className="flex-col overflow-hidden self-stretch relative flex aspect-square w-[152px] justify-center items-center rounded-[50%]">
                  <img
                    loading="lazy"
                    srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/12dceba2b992baa4afa1518bab3bb980d5144e9ded4c10831fec7aa6312121de?apiKey=e16cb3c994984815b737f967d633609a&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/12dceba2b992baa4afa1518bab3bb980d5144e9ded4c10831fec7aa6312121de?apiKey=e16cb3c994984815b737f967d633609a&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/12dceba2b992baa4afa1518bab3bb980d5144e9ded4c10831fec7aa6312121de?apiKey=e16cb3c994984815b737f967d633609a&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/12dceba2b992baa4afa1518bab3bb980d5144e9ded4c10831fec7aa6312121de?apiKey=e16cb3c994984815b737f967d633609a&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/12dceba2b992baa4afa1518bab3bb980d5144e9ded4c10831fec7aa6312121de?apiKey=e16cb3c994984815b737f967d633609a&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/12dceba2b992baa4afa1518bab3bb980d5144e9ded4c10831fec7aa6312121de?apiKey=e16cb3c994984815b737f967d633609a&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/12dceba2b992baa4afa1518bab3bb980d5144e9ded4c10831fec7aa6312121de?apiKey=e16cb3c994984815b737f967d633609a&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/12dceba2b992baa4afa1518bab3bb980d5144e9ded4c10831fec7aa6312121de?apiKey=e16cb3c994984815b737f967d633609a&"
                    className="absolute h-full w-full object-cover object-center inset-0"
                  />{" "}
                  <img
                    loading="lazy"
                    srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/12dceba2b992baa4afa1518bab3bb980d5144e9ded4c10831fec7aa6312121de?apiKey=e16cb3c994984815b737f967d633609a&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/12dceba2b992baa4afa1518bab3bb980d5144e9ded4c10831fec7aa6312121de?apiKey=e16cb3c994984815b737f967d633609a&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/12dceba2b992baa4afa1518bab3bb980d5144e9ded4c10831fec7aa6312121de?apiKey=e16cb3c994984815b737f967d633609a&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/12dceba2b992baa4afa1518bab3bb980d5144e9ded4c10831fec7aa6312121de?apiKey=e16cb3c994984815b737f967d633609a&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/12dceba2b992baa4afa1518bab3bb980d5144e9ded4c10831fec7aa6312121de?apiKey=e16cb3c994984815b737f967d633609a&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/12dceba2b992baa4afa1518bab3bb980d5144e9ded4c10831fec7aa6312121de?apiKey=e16cb3c994984815b737f967d633609a&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/12dceba2b992baa4afa1518bab3bb980d5144e9ded4c10831fec7aa6312121de?apiKey=e16cb3c994984815b737f967d633609a&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/12dceba2b992baa4afa1518bab3bb980d5144e9ded4c10831fec7aa6312121de?apiKey=e16cb3c994984815b737f967d633609a&"
                    className="aspect-square object-contain object-center w-full overflow-hidden rounded-[50%]"
                  />
                </div>
              </div>{" "}
              <div className="text-black text-lg font-bold self-center whitespace-nowrap mt-7">
                Dr. Abhay Mishra
              </div>{" "}
              <div className="text-black text-opacity-60 text-center text-sm self-center whitespace-nowrap mt-3">
                Korba Chhattisgarh India
              </div>{" "}
              <div className="text-rose-600 text-center text-sm font-bold tracking-wide uppercase whitespace-nowrap bg-rose-400 bg-opacity-30 self-center justify-center items-stretch mt-3.5 px-12 py-3.5 rounded-md max-md:px-5">
                Neurologist
              </div>{" "}
              <div className="bg-black bg-opacity-10 shrink-0 h-px mt-4" />{" "}
              <div className="bg-black bg-opacity-10 z-[1] shrink-0 h-px" />{" "}
              <div className="self-center flex w-[293px] max-w-full justify-between gap-5 mt-3.5 items-start">
                <div className="flex items-stretch gap-1.5">
                  <div className="flex-col overflow-hidden relative flex aspect-square w-6 justify-center items-center">
                    <img
                      loading="lazy"
                      src="https://cdn.builder.io/api/v1/image/assets/TEMP/410eb71f68379fafacada1a73fea87cbb1660090d8876e44b5dbabeede030c1e?apiKey=e16cb3c994984815b737f967d633609a&"
                      className="absolute h-full w-full object-cover object-center inset-0"
                    />{" "}
                    <img
                      loading="lazy"
                      src="https://cdn.builder.io/api/v1/image/assets/TEMP/410eb71f68379fafacada1a73fea87cbb1660090d8876e44b5dbabeede030c1e?apiKey=e16cb3c994984815b737f967d633609a&"
                      className="aspect-square object-contain object-center w-full overflow-hidden"
                    />
                  </div>{" "}
                  <div className="text-black text-opacity-60 text-center text-sm tracking-wide capitalize self-center grow whitespace-nowrap my-auto">
                    availability
                  </div>
                </div>{" "}
                <div className="flex items-stretch gap-1.5">
                  <div className="flex-col overflow-hidden relative flex aspect-square w-6 justify-center items-center">
                    <img
                      loading="lazy"
                      src="https://cdn.builder.io/api/v1/image/assets/TEMP/50d225bc836481ce3bd0f3f313def6bc4f320564ec8e3ce41ac36ef7b95069f5?apiKey=e16cb3c994984815b737f967d633609a&"
                      className="absolute h-full w-full object-cover object-center inset-0"
                    />{" "}
                    <img
                      loading="lazy"
                      src="https://cdn.builder.io/api/v1/image/assets/TEMP/50d225bc836481ce3bd0f3f313def6bc4f320564ec8e3ce41ac36ef7b95069f5?apiKey=e16cb3c994984815b737f967d633609a&"
                      className="aspect-square object-contain object-center w-full overflow-hidden"
                    />
                  </div>{" "}
                  <div className="text-black text-opacity-60 text-center text-sm tracking-wide capitalize self-center grow whitespace-nowrap my-auto">
                    Call Now
                  </div>
                </div>
              </div>
            </div>
          </div>{" "}
          <div className="flex flex-col items-stretch w-[33%] ml-5 max-md:w-full max-md:ml-0">
            <div className="shadow-sm bg-white flex w-full grow flex-col items-stretch mx-auto pt-9 pb-2.5 rounded-xl max-md:mt-10">
              <div className="flex items-center justify-between gap-4 pr-20 max-md:pr-5">
                <div className="flex-col overflow-hidden relative flex aspect-[2.25] items-stretch gap-1.5 my-auto pl-1.5 pr-8 py-2 max-md:pr-5">
                  <img
                    loading="lazy"
                    srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/569ac3d329d21db1e8871e83aad68acdc54229c30b03177c195faca3923e9798?apiKey=e16cb3c994984815b737f967d633609a&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/569ac3d329d21db1e8871e83aad68acdc54229c30b03177c195faca3923e9798?apiKey=e16cb3c994984815b737f967d633609a&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/569ac3d329d21db1e8871e83aad68acdc54229c30b03177c195faca3923e9798?apiKey=e16cb3c994984815b737f967d633609a&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/569ac3d329d21db1e8871e83aad68acdc54229c30b03177c195faca3923e9798?apiKey=e16cb3c994984815b737f967d633609a&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/569ac3d329d21db1e8871e83aad68acdc54229c30b03177c195faca3923e9798?apiKey=e16cb3c994984815b737f967d633609a&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/569ac3d329d21db1e8871e83aad68acdc54229c30b03177c195faca3923e9798?apiKey=e16cb3c994984815b737f967d633609a&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/569ac3d329d21db1e8871e83aad68acdc54229c30b03177c195faca3923e9798?apiKey=e16cb3c994984815b737f967d633609a&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/569ac3d329d21db1e8871e83aad68acdc54229c30b03177c195faca3923e9798?apiKey=e16cb3c994984815b737f967d633609a&"
                    className="absolute h-full w-full object-cover object-center inset-0"
                  />{" "}
                  <div className="flex-col relative overflow-hidden flex aspect-square justify-center items-center flex-1">
                    <img
                      loading="lazy"
                      src="https://cdn.builder.io/api/v1/image/assets/TEMP/7ea48d6964e746011e616915f0dee1704705bb601188e1fafc1c8a1bf42d4c6b?apiKey=e16cb3c994984815b737f967d633609a&"
                      className="absolute h-full w-full object-cover object-center inset-0"
                    />{" "}
                    <img
                      loading="lazy"
                      src="https://cdn.builder.io/api/v1/image/assets/TEMP/7ea48d6964e746011e616915f0dee1704705bb601188e1fafc1c8a1bf42d4c6b?apiKey=e16cb3c994984815b737f967d633609a&"
                      className="aspect-square object-contain object-center w-full overflow-hidden"
                    />
                  </div>{" "}
                  <div className="relative text-black text-sm font-bold self-center my-auto">
                    4.3
                  </div>
                </div>{" "}
                <div className="flex-col overflow-hidden self-stretch relative flex aspect-square w-[152px] justify-center items-center rounded-[50%]">
                  <img
                    loading="lazy"
                    srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/0aa97b783285d653480ceac035dc32e730fbbbe570d9aea9d3c12256ad9caac2?apiKey=e16cb3c994984815b737f967d633609a&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/0aa97b783285d653480ceac035dc32e730fbbbe570d9aea9d3c12256ad9caac2?apiKey=e16cb3c994984815b737f967d633609a&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/0aa97b783285d653480ceac035dc32e730fbbbe570d9aea9d3c12256ad9caac2?apiKey=e16cb3c994984815b737f967d633609a&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/0aa97b783285d653480ceac035dc32e730fbbbe570d9aea9d3c12256ad9caac2?apiKey=e16cb3c994984815b737f967d633609a&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/0aa97b783285d653480ceac035dc32e730fbbbe570d9aea9d3c12256ad9caac2?apiKey=e16cb3c994984815b737f967d633609a&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/0aa97b783285d653480ceac035dc32e730fbbbe570d9aea9d3c12256ad9caac2?apiKey=e16cb3c994984815b737f967d633609a&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/0aa97b783285d653480ceac035dc32e730fbbbe570d9aea9d3c12256ad9caac2?apiKey=e16cb3c994984815b737f967d633609a&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/0aa97b783285d653480ceac035dc32e730fbbbe570d9aea9d3c12256ad9caac2?apiKey=e16cb3c994984815b737f967d633609a&"
                    className="absolute h-full w-full object-cover object-center inset-0"
                  />{" "}
                  <img
                    loading="lazy"
                    srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/0aa97b783285d653480ceac035dc32e730fbbbe570d9aea9d3c12256ad9caac2?apiKey=e16cb3c994984815b737f967d633609a&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/0aa97b783285d653480ceac035dc32e730fbbbe570d9aea9d3c12256ad9caac2?apiKey=e16cb3c994984815b737f967d633609a&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/0aa97b783285d653480ceac035dc32e730fbbbe570d9aea9d3c12256ad9caac2?apiKey=e16cb3c994984815b737f967d633609a&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/0aa97b783285d653480ceac035dc32e730fbbbe570d9aea9d3c12256ad9caac2?apiKey=e16cb3c994984815b737f967d633609a&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/0aa97b783285d653480ceac035dc32e730fbbbe570d9aea9d3c12256ad9caac2?apiKey=e16cb3c994984815b737f967d633609a&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/0aa97b783285d653480ceac035dc32e730fbbbe570d9aea9d3c12256ad9caac2?apiKey=e16cb3c994984815b737f967d633609a&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/0aa97b783285d653480ceac035dc32e730fbbbe570d9aea9d3c12256ad9caac2?apiKey=e16cb3c994984815b737f967d633609a&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/0aa97b783285d653480ceac035dc32e730fbbbe570d9aea9d3c12256ad9caac2?apiKey=e16cb3c994984815b737f967d633609a&"
                    className="aspect-square object-contain object-center w-full overflow-hidden rounded-[50%]"
                  />
                </div>
              </div>{" "}
              <div className="text-black text-lg font-bold self-center whitespace-nowrap mt-7">
                Dr. Abhay Mishra
              </div>{" "}
              <div className="text-black text-opacity-60 text-center text-sm self-center whitespace-nowrap mt-3">
                Korba Chhattisgarh India
              </div>{" "}
              <div className="text-rose-600 text-center text-sm font-bold tracking-wide uppercase whitespace-nowrap bg-rose-400 bg-opacity-30 self-center justify-center items-stretch mt-3.5 px-12 py-3.5 rounded-md max-md:px-5">
                Neurologist
              </div>{" "}
              <div className="bg-black bg-opacity-10 shrink-0 h-px mt-4" />{" "}
              <div className="bg-black bg-opacity-10 z-[1] shrink-0 h-px" />{" "}
              <div className="self-center flex w-[293px] max-w-full justify-between gap-5 mt-3.5 items-start">
                <div className="flex items-stretch gap-1.5">
                  <div className="flex-col overflow-hidden relative flex aspect-square w-6 justify-center items-center">
                    <img
                      loading="lazy"
                      src="https://cdn.builder.io/api/v1/image/assets/TEMP/a8eca8ddee12d25e0d12fe8dbc25f50b7d01d69a629e76697f35674abf73d33e?apiKey=e16cb3c994984815b737f967d633609a&"
                      className="absolute h-full w-full object-cover object-center inset-0"
                    />{" "}
                    <img
                      loading="lazy"
                      src="https://cdn.builder.io/api/v1/image/assets/TEMP/a8eca8ddee12d25e0d12fe8dbc25f50b7d01d69a629e76697f35674abf73d33e?apiKey=e16cb3c994984815b737f967d633609a&"
                      className="aspect-square object-contain object-center w-full overflow-hidden"
                    />
                  </div>{" "}
                  <div className="text-black text-opacity-60 text-center text-sm tracking-wide capitalize self-center grow whitespace-nowrap my-auto">
                    availability
                  </div>
                </div>{" "}
                <div className="flex items-stretch gap-1.5">
                  <div className="flex-col overflow-hidden relative flex aspect-square w-6 justify-center items-center">
                    <img
                      loading="lazy"
                      src="https://cdn.builder.io/api/v1/image/assets/TEMP/74dbb926960ed297fb0b87aa2cab5ed744ce73060614330d493c7638b7556050?apiKey=e16cb3c994984815b737f967d633609a&"
                      className="absolute h-full w-full object-cover object-center inset-0"
                    />{" "}
                    <img
                      loading="lazy"
                      src="https://cdn.builder.io/api/v1/image/assets/TEMP/74dbb926960ed297fb0b87aa2cab5ed744ce73060614330d493c7638b7556050?apiKey=e16cb3c994984815b737f967d633609a&"
                      className="aspect-square object-contain object-center w-full overflow-hidden"
                    />
                  </div>{" "}
                  <div className="text-black text-opacity-60 text-center text-sm tracking-wide capitalize self-center grow whitespace-nowrap my-auto">
                    Call Now
                  </div>
                </div>
              </div>
            </div>
          </div>{" "}
          <div className="flex flex-col items-stretch w-[33%] ml-5 max-md:w-full max-md:ml-0">
            <div className="shadow-sm bg-white flex w-full grow flex-col items-stretch mx-auto pt-9 pb-2.5 rounded-xl max-md:mt-10">
              <div className="flex items-center justify-between gap-4 pr-20 max-md:pr-5">
                <div className="flex-col overflow-hidden relative flex aspect-[2.25] items-stretch gap-1.5 my-auto pl-1.5 pr-8 py-2 max-md:pr-5">
                  <img
                    loading="lazy"
                    srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/49b41818c17a464f735cba41cbd304994417b1a1a5b7da30f634007b28549ff0?apiKey=e16cb3c994984815b737f967d633609a&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/49b41818c17a464f735cba41cbd304994417b1a1a5b7da30f634007b28549ff0?apiKey=e16cb3c994984815b737f967d633609a&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/49b41818c17a464f735cba41cbd304994417b1a1a5b7da30f634007b28549ff0?apiKey=e16cb3c994984815b737f967d633609a&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/49b41818c17a464f735cba41cbd304994417b1a1a5b7da30f634007b28549ff0?apiKey=e16cb3c994984815b737f967d633609a&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/49b41818c17a464f735cba41cbd304994417b1a1a5b7da30f634007b28549ff0?apiKey=e16cb3c994984815b737f967d633609a&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/49b41818c17a464f735cba41cbd304994417b1a1a5b7da30f634007b28549ff0?apiKey=e16cb3c994984815b737f967d633609a&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/49b41818c17a464f735cba41cbd304994417b1a1a5b7da30f634007b28549ff0?apiKey=e16cb3c994984815b737f967d633609a&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/49b41818c17a464f735cba41cbd304994417b1a1a5b7da30f634007b28549ff0?apiKey=e16cb3c994984815b737f967d633609a&"
                    className="absolute h-full w-full object-cover object-center inset-0"
                  />{" "}
                  <div className="flex-col relative overflow-hidden flex aspect-square justify-center items-center flex-1">
                    <img
                      loading="lazy"
                      src="https://cdn.builder.io/api/v1/image/assets/TEMP/4d4fd040f7eda2278bd3630ef96704cf524cce160d77165aaf5974c5dcc20b8b?apiKey=e16cb3c994984815b737f967d633609a&"
                      className="absolute h-full w-full object-cover object-center inset-0"
                    />{" "}
                    <img
                      loading="lazy"
                      src="https://cdn.builder.io/api/v1/image/assets/TEMP/4d4fd040f7eda2278bd3630ef96704cf524cce160d77165aaf5974c5dcc20b8b?apiKey=e16cb3c994984815b737f967d633609a&"
                      className="aspect-square object-contain object-center w-full overflow-hidden"
                    />
                  </div>{" "}
                  <div className="relative text-black text-sm font-bold self-center my-auto">
                    4.3
                  </div>
                </div>{" "}
                <div className="flex-col overflow-hidden self-stretch relative flex aspect-square w-[152px] justify-center items-center rounded-[50%]">
                  <img
                    loading="lazy"
                    srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/c4ae54ef1a0e197a736f2fe1f1c86a8d7e579c00d23bc603125dfab97febb265?apiKey=e16cb3c994984815b737f967d633609a&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/c4ae54ef1a0e197a736f2fe1f1c86a8d7e579c00d23bc603125dfab97febb265?apiKey=e16cb3c994984815b737f967d633609a&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/c4ae54ef1a0e197a736f2fe1f1c86a8d7e579c00d23bc603125dfab97febb265?apiKey=e16cb3c994984815b737f967d633609a&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/c4ae54ef1a0e197a736f2fe1f1c86a8d7e579c00d23bc603125dfab97febb265?apiKey=e16cb3c994984815b737f967d633609a&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/c4ae54ef1a0e197a736f2fe1f1c86a8d7e579c00d23bc603125dfab97febb265?apiKey=e16cb3c994984815b737f967d633609a&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/c4ae54ef1a0e197a736f2fe1f1c86a8d7e579c00d23bc603125dfab97febb265?apiKey=e16cb3c994984815b737f967d633609a&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/c4ae54ef1a0e197a736f2fe1f1c86a8d7e579c00d23bc603125dfab97febb265?apiKey=e16cb3c994984815b737f967d633609a&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/c4ae54ef1a0e197a736f2fe1f1c86a8d7e579c00d23bc603125dfab97febb265?apiKey=e16cb3c994984815b737f967d633609a&"
                    className="absolute h-full w-full object-cover object-center inset-0"
                  />{" "}
                  <img
                    loading="lazy"
                    srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/c4ae54ef1a0e197a736f2fe1f1c86a8d7e579c00d23bc603125dfab97febb265?apiKey=e16cb3c994984815b737f967d633609a&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/c4ae54ef1a0e197a736f2fe1f1c86a8d7e579c00d23bc603125dfab97febb265?apiKey=e16cb3c994984815b737f967d633609a&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/c4ae54ef1a0e197a736f2fe1f1c86a8d7e579c00d23bc603125dfab97febb265?apiKey=e16cb3c994984815b737f967d633609a&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/c4ae54ef1a0e197a736f2fe1f1c86a8d7e579c00d23bc603125dfab97febb265?apiKey=e16cb3c994984815b737f967d633609a&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/c4ae54ef1a0e197a736f2fe1f1c86a8d7e579c00d23bc603125dfab97febb265?apiKey=e16cb3c994984815b737f967d633609a&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/c4ae54ef1a0e197a736f2fe1f1c86a8d7e579c00d23bc603125dfab97febb265?apiKey=e16cb3c994984815b737f967d633609a&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/c4ae54ef1a0e197a736f2fe1f1c86a8d7e579c00d23bc603125dfab97febb265?apiKey=e16cb3c994984815b737f967d633609a&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/c4ae54ef1a0e197a736f2fe1f1c86a8d7e579c00d23bc603125dfab97febb265?apiKey=e16cb3c994984815b737f967d633609a&"
                    className="aspect-square object-contain object-center w-full overflow-hidden rounded-[50%]"
                  />
                </div>
              </div>{" "}
              <div className="text-black text-lg font-bold self-center whitespace-nowrap mt-7">
                Dr. Abhay Mishra
              </div>{" "}
              <div className="text-black text-opacity-60 text-center text-sm self-center whitespace-nowrap mt-3">
                Korba Chhattisgarh India
              </div>{" "}
              <div className="text-rose-600 text-center text-sm font-bold tracking-wide uppercase whitespace-nowrap bg-rose-400 bg-opacity-30 self-center justify-center items-stretch mt-3.5 px-12 py-3.5 rounded-md max-md:px-5">
                Neurologist
              </div>{" "}
              <div className="bg-black bg-opacity-10 shrink-0 h-px mt-4" />{" "}
              <div className="bg-black bg-opacity-10 z-[1] shrink-0 h-px" />{" "}
              <div className="self-center flex w-[293px] max-w-full justify-between gap-5 mt-3.5 items-start">
                <div className="flex items-stretch gap-1.5">
                  <div className="flex-col overflow-hidden relative flex aspect-square w-6 justify-center items-center">
                    <img
                      loading="lazy"
                      src="https://cdn.builder.io/api/v1/image/assets/TEMP/36216b9e1562b35e48e7dc48c1706b0f485a46e07107a1a8bf922bd40133d355?apiKey=e16cb3c994984815b737f967d633609a&"
                      className="absolute h-full w-full object-cover object-center inset-0"
                    />{" "}
                    <img
                      loading="lazy"
                      src="https://cdn.builder.io/api/v1/image/assets/TEMP/36216b9e1562b35e48e7dc48c1706b0f485a46e07107a1a8bf922bd40133d355?apiKey=e16cb3c994984815b737f967d633609a&"
                      className="aspect-square object-contain object-center w-full overflow-hidden"
                    />
                  </div>{" "}
                  <div className="text-black text-opacity-60 text-center text-sm tracking-wide capitalize self-center grow whitespace-nowrap my-auto">
                    availability
                  </div>
                </div>{" "}
                <div className="flex items-stretch gap-1.5">
                  <div className="flex-col overflow-hidden relative flex aspect-square w-6 justify-center items-center">
                    <img
                      loading="lazy"
                      src="https://cdn.builder.io/api/v1/image/assets/TEMP/285ea541e03154429b3f7e56fe991c4e8d1fe9d174025f0e15c5eec17f79eb93?apiKey=e16cb3c994984815b737f967d633609a&"
                      className="absolute h-full w-full object-cover object-center inset-0"
                    />{" "}
                    <img
                      loading="lazy"
                      src="https://cdn.builder.io/api/v1/image/assets/TEMP/285ea541e03154429b3f7e56fe991c4e8d1fe9d174025f0e15c5eec17f79eb93?apiKey=e16cb3c994984815b737f967d633609a&"
                      className="aspect-square object-contain object-center w-full overflow-hidden"
                    />
                  </div>{" "}
                  <div className="text-black text-opacity-60 text-center text-sm tracking-wide capitalize self-center grow whitespace-nowrap my-auto">
                    Call Now
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>{" "}
      <div className="flex w-full flex-col justify-center items-stretch mt-44 px-px max-md:max-w-full max-md:mt-10">
        <div className="overflow-hidden pt-12 px-14 max-md:max-w-full max-md:px-5">
          <div className="gap-5 flex max-md:flex-col max-md:items-stretch max-md:gap-0">
            <div className="flex flex-col items-stretch w-[52%] max-md:w-full max-md:ml-0">
              <div className="bg-white flex flex-col items-stretch w-full px-10 py-8 rounded-2xl max-md:max-w-full max-md:mt-10 max-md:px-5">
                <div className="text-black text-opacity-50 text-base max-md:max-w-full">
                  Name
                </div>{" "}
                <div className="text-black text-opacity-50 text-base whitespace-nowrap bg-rose-400 bg-opacity-10 justify-center mt-5 pl-4 pr-16 py-5 rounded-lg items-start max-md:max-w-full max-md:pr-5">
                  Enter Your Full Name
                </div>{" "}
                <div className="text-black text-opacity-50 text-base mt-5 max-md:max-w-full">
                  Problem
                </div>{" "}
                <div className="text-black text-opacity-50 text-base whitespace-nowrap bg-rose-400 bg-opacity-10 mt-5 pl-4 pr-16 pt-8 pb-20 rounded-lg items-start max-md:max-w-full max-md:pr-5">
                  Enter Your Problem in detail
                </div>{" "}
                <div className="text-black text-opacity-50 text-base mt-5 max-md:max-w-full">
                  Schedule Time
                </div>{" "}
                <div className="bg-rose-400 bg-opacity-10 flex items-center justify-between gap-5 mt-5 px-3 py-4 rounded-lg max-md:max-w-full max-md:flex-wrap">
                  <div className="text-black text-opacity-50 text-base my-auto">
                    Select your Appointment Time
                  </div>{" "}
                  <img
                    loading="lazy"
                    src="https://cdn.builder.io/api/v1/image/assets/TEMP/ed2c18cd43eefbfdc79cfe6ef2b27040f5f6a9b90f5efa23df5ba313c6e7c786?apiKey=e16cb3c994984815b737f967d633609a&"
                    className="aspect-square object-contain object-center w-[34px] overflow-hidden self-stretch shrink-0 max-w-full"
                  />
                </div>{" "}
                <div className="text-white text-center text-2xl font-semibold whitespace-nowrap rounded bg-rose-500 justify-center items-center mt-5 px-16 py-4 max-md:max-w-full max-md:px-5">
                  Book Appointment
                </div>
              </div>
            </div>{" "}
            <div className="flex flex-col items-stretch w-[48%] ml-5 max-md:w-full max-md:ml-0">
              <img
                loading="lazy"
                srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/36712ce566ab8960fc5d78986232444c064d2dc64e633fe83ba15442a8dabedd?apiKey=e16cb3c994984815b737f967d633609a&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/36712ce566ab8960fc5d78986232444c064d2dc64e633fe83ba15442a8dabedd?apiKey=e16cb3c994984815b737f967d633609a&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/36712ce566ab8960fc5d78986232444c064d2dc64e633fe83ba15442a8dabedd?apiKey=e16cb3c994984815b737f967d633609a&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/36712ce566ab8960fc5d78986232444c064d2dc64e633fe83ba15442a8dabedd?apiKey=e16cb3c994984815b737f967d633609a&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/36712ce566ab8960fc5d78986232444c064d2dc64e633fe83ba15442a8dabedd?apiKey=e16cb3c994984815b737f967d633609a&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/36712ce566ab8960fc5d78986232444c064d2dc64e633fe83ba15442a8dabedd?apiKey=e16cb3c994984815b737f967d633609a&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/36712ce566ab8960fc5d78986232444c064d2dc64e633fe83ba15442a8dabedd?apiKey=e16cb3c994984815b737f967d633609a&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/36712ce566ab8960fc5d78986232444c064d2dc64e633fe83ba15442a8dabedd?apiKey=e16cb3c994984815b737f967d633609a&"
                className="aspect-[0.94] object-contain object-center w-full overflow-hidden grow mt-7 max-md:max-w-full max-md:mt-10"
              />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default MyComponent